version: "3"

services:
  haproxy:
    image: haproxy:2.3-alpine
    container_name: haproxy
    ports:
      - 8000:6301
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - gateway-network
  
  ng1:
    build:
      context: ./
      dockerfile: ./dockerfile-nginx
    container_name: ng1
    volumes:
      - ./kv-ng1.conf:/etc/keepalived/keepalived.conf
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
      - ./index-master.html:/usr/share/nginx/html/index.html
    networks:
      gateway-network:
        ipv4_address: 172.20.128.11
    cap_add: 
      - NET_ADMIN
  
  ng2:
    build:
      context: ./
      dockerfile: ./dockerfile-nginx
    container_name: ng2
    volumes:
      - ./kv-ng2.conf:/etc/keepalived/keepalived.conf
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
      - ./index-slave.html:/usr/share/nginx/html/index.html
    networks:
      gateway-network:
        ipv4_address: 172.20.128.12
    cap_add: 
        - NET_ADMIN

networks:
  gateway-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16