version: '3.1'

services:
  zk1:
    image: zookeeper
    restart: always
    hostname: zk1
    container_name: zk1
    ports:
      - 2181:2181
    volumes:
      - /usr/local/data/zookeeper/zk1/data:/data
      - /usr/local/data/zookeeper/zk1/log:/datalog
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181

  zk2:
    image: zookeeper
    restart: always
    hostname: zk2
    container_name: zk2
    ports:
      - 2182:2181
    volumes:
      - /usr/local/data/zookeeper/zk2/data:/data
      - /usr/local/data/zookeeper/zk2/log:/datalog
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zk3:2888:3888;2181

  zk3:
    image: zookeeper
    restart: always
    hostname: zk3
    container_name: zk3
    ports:
      - 2183:2181
    volumes:
      - /usr/local/data/zookeeper/zk3/data:/data
      - /usr/local/data/zookeeper/zk3/log:/datalog
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
