version: '3'

services:
  es:
    image: elasticsearch:6.8.14
    container_name: es
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/9200/data:/usr/share/elasticsearch/data
      - ./data/9200/log:/usr/share/elasticsearch/logs
      - ./data/9200/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:rw
    mem_limit: 1024m
    restart: always
  
  kibana:
    image: kibana:6.8.14
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:rw
    depends_on:
      - es
    mem_limit: 512m
    restart: always