version: '3.1'

services:
  centos-dev:
    image: zhang1career/centos-dev:0.5
    container_name: php-cpp
    privileged: true
    ports:
      - "2222:22"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /Users/zhangrj/Projects/nicetuan/php-src:/data/projects/php-src:rw
      - /Users/zhangrj/Projects/nicetuan/php-bin:/data/projects/php-bin:rw
      - /Users/zhangrj/Projects/nicetuan/php-cpp:/data/projects/php-cpp:rw
    cap_add:
      - SYS_PTRACE
    command:
      - /usr/sbin/init