version: '3.7'
services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql
    restart: always
    volumes:
      - ./data/mysql/var:/var/lib/mysql
      - ./data/mysql/conf/mysqld.cnf:/etc/my.cnf
      - ./data/mysql/log:/var/log
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_USER: zhangrj
      MYSQL_PASSWORD: 123123
    ports:
      - 3306:3306
  
  php-fpm:
    image: php:fpm-alpine
    container_name: php-fpm
    restart: always
    volumes:
      - ./data/php-fpm/conf/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./data/php-fpm/conf/php-fpm.d:/usr/local/etc/php-fpm.d
      - ./data/php-fpm/log:/usr/local/var/log
      - ./data/app:/usr/share/nginx/html
    ports: 
      - 9000:9000
  
  nginx:
    image: nginx:stable
    container_name: nginx
    restart: always
    volumes: 
      - ./data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/conf/conf.d:/etc/nginx/conf.d
      - ./data/app:/usr/share/nginx/html
      - ./data/nginx/log:/var/log/nginx
    ports: 
      - 10080:80
      - 10443:443
    links:
      - php-fpm:php-fpm